version: '3.4'

services:
  lab.todo.api:
    image: labtodoweb_lab.todo.api:latest
    build:
      context: .
      dockerfile: Lab.Todo.Api/Dockerfile
    environment:
      ASPNETCORE_URLS: "https://+;http://+"
      ASPNETCORE_HTTPS_PORT: "5003"
      ASPNETCORE_ENVIRONMENT: "Development"
    ports:
      - "5002:80"
      - "5003:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${USERPROFILE}\.aspnet\https:/root/.aspnet/https:ro
    depends_on:
      - lab.todo.database
  lab.todo.web:
    image: labtodoweb_lab.todo.web:latest
    build:
      context: .
      dockerfile: Lab.Todo.Web/Dockerfile
    ports:
      - "5000:80"
      - "5001:443"
    environment:
      ASPNETCORE_URLS: "https://+;http://+"
      ASPNETCORE_HTTPS_PORT: "5001"
      ASPNETCORE_ENVIRONMENT: "Development"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${USERPROFILE}/.aspnet/https:/root/.aspnet/https:ro
    depends_on:
      - lab.todo.database
  lab.todo.database:
    image: labtodoweb_lab.todo.database:latest
    build:
     context: .
     dockerfile: Lab.Todo.Database/Dockerfile
    ports:
      - "5005:1433"
    environment:
      SA_PASSWORD: "tmpPassword123"
      ACCEPT_EULA: "Y"
